"""add player profiles

Revision ID: 930149834383
Revises: 09712a2af161
Create Date: 2026-05-05 17:30:53.846560

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '930149834383'
down_revision: Union[str, None] = '09712a2af161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=True),
    sa.Column('document_number', sa.String(length=50), nullable=True),
    sa.Column('phone_country', sa.String(length=10), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('uniform_size', sa.String(length=10), nullable=True),
    sa.Column('level', sa.String(length=30), nullable=True),
    sa.Column('wins', sa.Integer(), server_default='0', nullable=False),
    sa.Column('losses', sa.Integer(), server_default='0', nullable=False),
    sa.Column('draws', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sport_characteristics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_class_payment_method', sa.String(length=30), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_profiles')
    # ### end Alembic commands ###
